### ISSUE TITLE
Display * for each entered password character …

### ISSUE THREAD

**Issue by 607011** [pinae/passwordGenerator-python#1]
… and force user to input it twice to check correct entry.

**Comment by pinae** [comment]
I think typing the password twice is not necessary. If you have a typo in the master password it will generate a password which does not work at the domain. If you try to login with that the website will display an error anyway. You could force the password twice for new domains but since we do not save the domains in this application we do not know when a domain is new.

Displaying \* could probably be done with the readline library but that would make the program more complicated and harder to understand. I understand that this limitation might make the software unfit for production use in some circumstances. For production use a fork could be extended or maybe even better the graphical tool could be used.

**Comment by Wikinaut** [comment]
An ad-hoc solution is to use getpass.getpass as proposed in this comment http://www.heise.de/forum/c-t/Kommentare-zu-c-t-Artikeln/Programmieren-lernen-mit-Python/Master-Passwort-nicht-anzeigen/posting-21117235/show/

```
 Master Passwort nicht anzeigen

Hallo,

angeregt von der tollen Idee habe ich ebenfalls eine kleine Anpassung vorgenommen:
Wenn man am Anfang des Programms neben pbkdf2_hmac auch getpass importiert:

import getpass

Und die Zeile:
master_password = import('Masterpasswort: ')

durch
master_password = getpass.getpass('Masterpasswort: ')

ersetzt, dann wird das Passwort bei der Eingabe nicht mehr ausgegeben.
```

**Comment by pinae** [comment]
The getpass solution is used at https://github.com/pinae/ctSESAM-python-memorizing.
